export enum AppRoute {
  Login = '/entrar',
  Visitors = '/visitantes',
  NewVisitor = '/visitantes/novo',
  People = '/pessoas',
  Coffee = '/cafe-de-boas-vindas',
  Classes = '/turma',
  Admin = '/menu',
  Settings = '/configuracoes',
  Volunteers = '/voluntarios',
  Reports = '/relatorios',
  Profile = '/perfil',
  ChangePassword = '/perfil/senha',
  IntegrationSignup = '/integracao/inscricao',
  MakeupAttendance = '/turma/reposicao',
  MembershipInterest = '/integracao/ficha-de-interesse',
  Members = '/membros',
  CommunityGroups = '/comunidade',
  Ministries = '/comunidade/ministerios',
  SmallGroups = '/comunidade/pgs',
  Store = '/loja',
  NewStoreItem = '/loja/novo',
  StorePublic = '/loja/reservar',
}
